version: "3.9"

services:
  coordinator:
    build: .
    container_name: coordinator
    command: >
      python ./coordinator/coordinator.py
      --num-workers 2
      --epochs 10
      --lr 0.1
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys
    networks:
      - training-net
    ports:
      - "5556:5556"   # handshake channel
      - "5557:5557"   # task channel
      - "5558:5558"   # result channel

  worker1:
    build: .
    container_name: worker1
    command: python ./worker/worker.py
    environment:
      WORKER_ID: "0"
      WORKER_MISBEHAVE: "1"
    networks:
      - training-net
    depends_on:
      - coordinator

  worker2:
    build: .
    container_name: worker2
    command: python ./worker/worker.py
    environment:
      WORKER_ID: "1"
    networks:
      - training-net
    depends_on:
      - coordinator


networks:
  training-net:
